Name:           ros-kinetic-libphidget21
Version:        0.7.1
Release:        0%{?dist}
Summary:        ROS libphidget21 package

Group:          Development/Libraries
License:        LGPL
URL:            http://ros.org/wiki/libphidget21
Source0:        %{name}-%{version}.tar.gz

Requires:       libusb-devel
BuildRequires:  libusb-devel
BuildRequires:  ros-kinetic-catkin

%description
This package wraps the libphidget21 to use it as a ROS dependency

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Mon May 22 2017 Martin Guenther <martin.guenther@dfki.de> - 0.7.1-0
- Autogenerated by Bloom

* Fri Feb 17 2017 Benjamin Maidel <benjamin.maidel@ipa.fraunhofer.de> - 0.7.0-0
- Autogenerated by Bloom

