Name:           ros-kinetic-phidgets-api
Version:        0.7.4
Release:        0%{?dist}
Summary:        ROS phidgets_api package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/phidgets_api
Source0:        %{name}-%{version}.tar.gz

Requires:       libusbx
Requires:       ros-kinetic-libphidget21
BuildRequires:  libusbx-devel
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-libphidget21

%description
A C++ Wrapper for the Phidgets C API

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Wed Oct 04 2017 Martin Guenther <martin.guenther@dfki.de> - 0.7.4-0
- Autogenerated by Bloom

* Fri Jun 30 2017 Martin Guenther <martin.guenther@dfki.de> - 0.7.3-0
- Autogenerated by Bloom

* Fri Jun 02 2017 Martin Guenther <martin.guenther@dfki.de> - 0.7.2-0
- Autogenerated by Bloom

* Mon May 22 2017 Martin Guenther <martin.guenther@dfki.de> - 0.7.1-0
- Autogenerated by Bloom

* Fri Feb 17 2017 Martin Guenther <martin.guenther@dfki.de> - 0.7.0-0
- Autogenerated by Bloom

